[package]
name = "controller_native"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28"
minifb = "0.28.0"
shared = { path = "../shared" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
